camunda.bpm:
  admin-user:
    id: kermit
    password: superSecret
    firstName: Kermit
  filter:
    create: All tasks
    
    
spring:
  h2:
    console:
      enabled: true
      path: /console/